/**
 * Runtime settings from /config.js (window.PABLOCH_CONFIG).
 *
 * config.js is owned by the site owner and never generated by the build.
 * Values are validated before use; anything malformed is ignored and the
 * server-rendered defaults stay in place.
 */
import { site, socialLinks, type SocialKey } from "../content/site.ts";

declare global {
  interface Window {
    PABLOCH_CONFIG?: unknown;
    __ptReady?: boolean;
  }
}

export interface RuntimeConfig {
  /** Web3Forms access key, or null when missing/placeholder. */
  web3formsKey: string | null;
  email: string;
  /** undefined → keep the default; null → owner blanked it, hide the link. */
  socials: Partial<Record<SocialKey, string | null>>;
}

const EMAIL_RE = /^[^\s@<>"']+@[^\s@<>"']+\.[a-z]{2,}$/i;
const HANDLE_RE = /^[A-Za-z0-9_.]{1,64}$/;
const KEY_RE = /^[A-Za-z0-9-]{20,80}$/;

const CONFIG_KEYS: Record<SocialKey, string> = {
  telegram: "TELEGRAM",
  instagram: "INSTAGRAM",
  facebook: "FACEBOOK",
};

let cached: RuntimeConfig | null = null;

export function readConfig(): RuntimeConfig {
  if (cached) return cached;
  const raw: Record<string, unknown> =
    typeof window.PABLOCH_CONFIG === "object" && window.PABLOCH_CONFIG !== null
      ? (window.PABLOCH_CONFIG as Record<string, unknown>)
      : {};
  const str = (key: string): string | undefined => (typeof raw[key] === "string" ? (raw[key] as string).trim() : undefined);

  const key = str("WEB3FORMS_KEY");
  const email = str("EMAIL");

  const socials: RuntimeConfig["socials"] = {};
  for (const s of socialLinks) {
    const value = str(CONFIG_KEYS[s.key]);
    if (value === undefined) continue;
    const handle = value.replace(/^@/, "");
    if (handle === "") socials[s.key] = null;
    else if (HANDLE_RE.test(handle)) socials[s.key] = handle;
  }

  cached = {
    web3formsKey: key && KEY_RE.test(key) && !/paste/i.test(key) ? key : null,
    email: email && EMAIL_RE.test(email) ? email : site.email,
    socials,
  };
  return cached;
}

/** Point every email and social link on the page at the configured values. */
export function applyConfig(config: RuntimeConfig): void {
  document.querySelectorAll<HTMLAnchorElement>("a[data-email-link]").forEach((a) => {
    a.href = `mailto:${config.email}`;
    const text = a.querySelector<HTMLElement>("[data-email-text]");
    if (text) text.textContent = config.email;
  });

  for (const s of socialLinks) {
    const handle = config.socials[s.key];
    if (handle === undefined) continue;
    document.querySelectorAll<HTMLAnchorElement>(`a[data-social="${s.key}"]`).forEach((a) => {
      const item = a.closest<HTMLElement>("[data-social-item]") ?? a;
      if (handle === null) {
        item.hidden = true;
        return;
      }
      a.href = `${s.base}${encodeURIComponent(handle)}`;
      const label = a.querySelector<HTMLElement>("[data-social-handle]");
      if (label) label.textContent = `@${handle}`;
    });
  }
}
